name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy to ec2
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/forum-api
            git pull origin main
            npm install
            npm run migrate up
            pm2 restart forum-api
